### ISSUE TITLE
Two versions of matjags available

### ISSUE THREAD

**Issue by Feezdev** [msteyvers/matjags#12]
Hi,

I have noticed that the github for matjags appear to have an older/different version of matjags than is available on the matjags website:

matjags website (version is 1.3.2) : http://psiexp.ss.uci.edu/research/programs_data/jags/
matjags github (version is 1.3.1) : https://github.com/msteyvers/matjags/blob/master/matjags.m

It seems as if the current github version is a fork from the original matjags from an ealier timepoint?

So far I can see a couple of differences:
1) matjags 1.3.2  has removed fullpath and instead navigates to temporary directories as necessary (probably not optimal)
2) matjags 1.3.2 has no adaptation
3) matjags 1.3.2 has no/different random seeds for each chain (no sure here)
4) matjags 1.3.2 has a 'getDICstats' inherited from matbugs that reads DIC stats from a jags text file output. However, jags returns DIC stats only with more than 2 chains in parallel, and I don't think this can be triggered by matjags as matjags instantiate multiple chains by running multiple 1 chains jags model in parallel, rather than asking jags to run the model with N chains (as with Rjags?). 
5) matjags 1.3.2 has no 'HDIofSamples' function.

Would it be useful to merge the 2 versions or would it be better to update the git-version of matjags ?

Best,
Vincent

**Comment by drbenvincent** [comment]
Hi
I got in touch with Mark Steyvers asking him to put the code up on GitHub, and he graciously agreed to do so. From that point, I did not keep up with any changes on his site... not sure if any were really made.

Since it was placed here on GitHub I an other people have made a few updates. So I believe this version on GitHub is the most recent. Although we've not really made the full transition to making it a GitHub project, in terms of version numbers and releases etc. The fact that you raise these issues probably means it's a good idea, even just to remove confusion.

I was brought on as a core dev a little while ago, and have made some updates in my fork, but my teaching and research duties have held me back from updating this repo much. But there are some ideas waiting to be acted on.

So thumbs up to releasing the current GitHub code as version 1.3.3 and going from there?

Ben

**Comment by msteyvers** [comment]
Hi Everyone,
I do not quite know why the versions differ. I have not made any significant changes to the local version that I have (certainly not anything having to do with the DIC calculation) and I am hoping that the GitHub version will serve as the most up to date version. 
-Mark
